language: node_js
node_js:
    - node

script:
    - npm run build
    - npm run test
deploy:
    provider: npm
    email: koliberr136a1@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
        tags: true
